### ISSUE TITLE
cannot provision

### ISSUE THREAD

**Issue by elstamey** [mdwheele/vm#57]
I'm having this error, not sure if it's related to the issues we were talking about earlier
======

````==> default: Agent pid 25998
==> default: Enter passphrase for /home/vagrant/.ssh/id_rsa: 
==> default: Bad passphrase, try again for /home/vagrant/.ssh/id_rsa: 
==> default: Bad passphrase, try again for /home/vagrant/.ssh/id_rsa: Bad passphrase, try again for /home/vagrant/.ssh/id_rsa: 
==> default: Bad passphrase, try again for /home/vagrant/.ssh/id_rsa: ````

**Comment by elstamey** [comment]
Or maybe this is related to github.ncsu.edu being down.  :(

**Comment by mdwheele** [comment]
Or it's a bad passphrase!

**Comment by elstamey** [comment]
I'm never given the chance to type a passphrase

**Comment by elstamey** [comment]
originally, I tried to add the phrase to my .bash_profile like you suggested and copied that to my 'files/dotfiles' dir.  I cannot get the provision to work now.

**Comment by mdwheele** [comment]
Oh dear. Don't put you passphrase in clear text of bash_profile. We can look at it tomorrow.

**Comment by elstamey** [comment]
I didn't put it in my .bash_profile at all.

**Comment by elstamey** [comment]
So I guess I did this:

if [ -z "$SSH_AUTH_SOCK" ] ; then
    eval $(ssh-agent -s)
    ssh-add
fi

with no definition of what the SSH_AUTH_SOCK was

**Comment by mdwheele** [comment]
We can look at it tomorrow. That works just fine for me. That's checking for an active `ssh-agent`. If none exists then start it and add all identities found in `/home/vagrant/.ssh`. It's asking for a passphrase and it looks like (by your error message) that you are being prompted for it and either entering a bad passphrase or nothing at all. 

That snippet you posted is in the baseline `.bash_profile` and is what I was asking you about today. 

IF you configure your instance of the VM to do ssh-agent forwarding through the `forward_ssh` option in `config.yaml`, then it will forward whatever is on your host machine and that will be that. Otherwise, if an ssh-agent is not found (be it forwarded from host or not started on guest) then it will be started by this entry in the baseline `.bash_profile`.

**Comment by elstamey** [comment]
I needed to work from home this morning because the cat is sick again. :'(

**Comment by elstamey** [comment]
I finally found something still in the bash_profile when I vagrant ssh'd.  I thought i could remove it from my vm dotfiles and re-provision.

**Comment by elstamey** [comment]
==> default: No Match for argument: git
==> default: http://install.linux.ncsu.edu/pub/yum/itecs/servers/eos-RHEL6-testing/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 403 Forbidden"
==> default: Trying other mirror.
==> default: Error: Cannot retrieve repository metadata (repomd.xml) for repository: eos-testing. Please verify its path and try again
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by elstamey** [comment]
And then once I cisco connected and auth'd my key before provisioning, I got it going.  Good grief.  I feel like I just pushed a car out of a muddy ditch.  I did, however roll back to pre-key commits.
